name: spain_bot_web_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  bloc: ^8.1.2
  cloud_firestore: ^4.9.2
  firebase_auth: ^4.10.0
  firebase_core: ^2.16.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  logger: ^2.0.2+1
  provider: ^6.0.5
  telegram_web_app_client:
    git:
      url: https://github.com/RuslanTsitser/telegram_web_app_client.git
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
